### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by kafcioo** [gges5110/React-Semantic-UI-Sortable-Table-Example#4]
There is a bug in this example 

When you add the same data 
for example :
  { name: 'John', age: 15, gender: 'Male' },
  { name: 'Amber', age: 40, gender: 'Female' },
  { name: 'Leslie', age: 25, gender: 'Female' },
  { name: 'Ben', age: 70, gender: 'Male' },
  { name: 'Ben', age: 70, gender: 'Male' },
  { name: 'Ben', age: 70, gender: 'Male' },

and then click table header to sort it will add more records until its unable to sort them

**Comment by gges5110** [comment]
@kafcioo Thanks for filing the bug! I have made a fix to it, let me know if it doesn't work.
